org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

# Can be music, tracker or lyrics
extType=music
extId=anikoto
extClass=AnikotoExtension

extIconUrl=https://anikototv.to/favicon.ico
extName=Anikoto
extDescription=Watch subbed and dubbed anime from Anikoto with multi-server streams and AniSkip support.

extAuthor=Echo
extAuthorUrl=https://github.com/itsmechinmoy

extRepoUrl=https://github.com/itsmechinmoy/echo-anikoto
extUpdateUrl=https://api.github.com/repos/itsmechinmoy/echo-anikoto/releases/
